# Generated by Django 3.0.2 on 2020-01-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_uuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
